# Site settings
title: Sawyer Greaves
email: greaves.sawyer@gmail.com
url: https://github.com/Rodeosocks/portfolio_website
description: "My Projects!"
keywords: "robotics, engineering, research, personal, academics"
skills: "Robotics - 3D Design - Controls"
meta_author: Greaves Sawyer

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sawyer Greaves
  location: Salt Lake City, Utah
  social: Socials
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/sawyer_greaves
  - title: instagram
    url: https://www.instagram.com/sawyer_greaves/
  - title: linkedin
    url: https://www.linkedin.com/in/sawyer-greaves-555616277/
  - title: github
    url: http://github.com/Rodeosocks

# Postal address (add as many lines as necessary)
address:
  - line: University of Utah
  - line: Magnetic and Medical Robotics Lab

# Credits content
credits: 'Thank you to <a href="http://startbootstrap.com">startbootstrap</a> and <a href="https://github.com/jeromelachaud">Jerome Lachaud</a> for the website template.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
